function addsandbox()
%     if ~isempty( ver( 'fcam' ) )
%         fx.fcam.command.addsandbox();
%         fx.fcam.command.disableaddon();
%     else
        thisPath = fileparts( mfilename( 'fullpath' ) );
        addpath( fullfile(...
            thisPath,...
            'code',...
            'fcam' ) );
        addpath( fullfile(...
            thisPath,...
            'test' ) );
%     end
end