function addsandbox()
    thisPath = fileparts( mfilename( 'fullpath' ) );
    addpath( fullfile(...
        thisPath,...
        'code',...
        'fcam' ), '-end' );
    addpath( fullfile(...
        thisPath,...
        'test' ), '-end' );
end