function rmsandbox()
    thisPath = fileparts( mfilename( 'fullpath' ) );
    rmpath( fullfile(...
        thisPath,...
        'code',...
        'fcam' ) );
    rmpath( fullfile(...
        thisPath,...
        'test' ) );
end